[[language]]
name = "nix"
language-servers = ["nix-analyzer"]
auto-format = true

[language-server.nix-analyzer]
command = "/home/josh/src/nix-analyzer/target/debug/nix-analyzer"

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", ".git"]
language-servers = ["pyright", "ruff"]
auto-format = true
formatter = {command = 'ruff', args = ["format", "-"]}

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"] 

[language-server.ruff]
command = "ruff"
args = ["lsp"] 

[language-server.texlab.build]
onSave = true

[language-server.awk-language-server]
command = "/var/home/josh/src/awk-language-server/server/out/cli.js"

[[language]]
name = "awk"
scope = "source.awk"
injection-regex = "awk"
file-types = ["awk", "gawk", "nawk", "mawk"]
comment-token = "#"
language-servers = [ "awk-language-server" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "/var/home/josh/src/cc.awk/node_modules/prettier/bin-prettier.js", args = ["--parser=awk-parse"]}
