[[language]]
name = "nix"
language-servers = ["nix-analyzer"]

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
language-servers = ["pyright"]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[language-server.nix-analyzer]
# command = "/home/josh/dev/nix-analyzer/outputs/out/bin/nix-analyzer"
# command = "/home/josh/dev/nix-analyzer-cpnp/nix-analyzer/target/debug/lsp"
command = "/home/josh/src/nix-analyzer/target/debug/nix-analyzer"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"] 

[language-server.vscode-json-language-server]
command = "json-languageserver"

[language-server.texlab.build]
onSave = true
